name = "gip"
version = "0.1.0"
defaultTargets = ["Gip"]

[[lean_lib]]
name = "Gip"

[[lean_lib]]
name = "Test"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.25.0"
